export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_ALL_FILTERS = 'CHANGE_ALL_FILTERS';
export const CHANGE_QUERY = 'CHANGE_QUERY';
export const CHANGE_DATE = 'CHANGE_DATE';
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS';
export const SELECT_EVENT = 'SELECT_EVENT';
export const SET_INTERESTED = 'SET_INTERESTED';